<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Appointments.Domain\Appointments.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-preview.2.26159.112" />
      <PackageReference Include="TimeWarp.Mediator" Version="13.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\" />
    </ItemGroup>
    
</Project>
